name: Docker Image CI

on:
    push:
        branches: [develop, releases/**, master]
    pull_request:
        branches: [develop, releases/**, master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: 输出当前分支名
              run: echo "当前分支为： $GITHUB_REF"

            - name: ENVFILE
              uses: alekangelov/secret-envfile@v1
              with:
                  content: ${{ secrets.ENV_FILE_DEV }}
                  filename: .env

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build the Developer Docker image
              id: docker_build_dev
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/vjing-backend-test:0.0.${{github.run_number}}
              if: ${{ github.ref == 'refs/heads/develop' }}

            - name: Build the Production Docker image
              id: docker_build_production
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/vjing-backend:0.0.${{github.run_number}}
              if: ${{ github.ref == 'refs/heads/master' }}

            - name: ssh scp ssh pipelines
              uses: cross-the-world/ssh-scp-ssh-pipelines@latest
              env:
                  WELCOME: "正地准备目录"
                  LASTSSH: "docker-compose"
              with:
                  host: ${{ secrets.SSH_DEV_HOST }}
                  user: ${{ secrets.SSH_DEV_USER }}
                  pass: ${{ secrets.SSH_DEV_PASSWORD }}
                  port: 22
                  connect_timeout: 10s
                  first_ssh: |
                      rm -rf /root/service/vjing-backend-test
                      mkdir -p /root/service/vjing-backend-test
                  scp: |
                      './docker-compose.yml' => "/root/service/vjing-backend-test/"
                      './.env' => "/root/service/vjing-backend-test"
                  last_ssh: |
                      echo $LASTSSH &&
                      docker-compose -f /root/service/vjing-backend-test/docker-compose.yml down &&
                      BUILD_VERSION="${{github.run_number}}" docker-compose -f /root/service/vjing-backend-test/docker-compose.yml up -d
